name: Python Test with Coverage Comment

on:
  pull_request:
  push:
    branches:
      - "main"


jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    env:
      AWS_ACCESS_KEY_ID: 123456
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: 123456
      DYNAMODB_ENDPOINT: http://192.168.0.16:8000
      ENVIRONMENT: testing
      FLASK_APP: app
      MERCADO_PAGO_URL: http://192.168.0.16:3001/mercado_pago
      SECRET_KEY: abcdeABCDE123456

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r engine/requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        working-directory: .
        run: |
          pytest --cov=engine.app \
                 --cov-config=.coveragerc \
                 --cov-report=term \
                 --cov-report=xml \
                 --cov-report=json \
                 --cov-fail-under=80 \
                 engine/tests

      - name: Comment coverage on PR
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
