name: Deploy Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Deploy Docker image
      run: |
        
        export NAME=$(cat engine/info.yaml | grep app-name | tr -d '[:space:]' | awk -F: '{print $2}')
        export VERSION=$(cat engine/info.yaml | grep app-version | tr -d '[:space:]' | awk -F: '{print $2}')
        
        docker build -t ghcr.io/$NAME engine/
        
        docker tag ghcr.io/$NAME ghcr.io/$NAME:$VERSION
        
        docker push ghcr.io/$NAME:$VERSION
        docker push ghcr.io/$NAME:latest