name: Python Test Automation

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: 123456
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: 123456
      DYNAMODB_ENDPOINT: http://192.168.0.16:8000
      ENVIRONMENT: testing
      FLASK_APP: app
      MERCADO_PAGO_URL: http://192.168.0.16:3005/mercado_pago
      SECRET_KEY: abcdeABCDE123456

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.0
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.0"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r engine/requirements.txt

      - name: Run unit tests
        working-directory: .
        run: |
          python -m unittest discover -s engine/tests -t .
